#!/usr/bin/env bash

# AKS options
##################

KUBECTL_VERSION="${KUBECTL_VERSION:-v1.15.5}"

AKS_CLUSTER_NAME="${AKS_CLUSTER_NAME:-$(whoami)-cap-$CLUSTER_NAME}"

AZURE_LOCATION="${AZURE_LOCATION:-westeu}"
AZURE_RESOURCE_GROUP="${AZURE_RESOURCE_GROUP:-}"
AZURE_APP_ID="${AZURE_APP_ID:-}"
AZURE_PASSWORD="${AZURE_PASSWORD:-}"
AZURE_TENANT_ID="${AZURE_TENANT_ID:-}"
